//package Exceptionday6;
//
//public class ExceptionDemo3 {
//
//	public static void main(String[] args) {
//		// TODO Auto-generated method stub
//		System.out.println("program task started");
//
//		try {
//			System.out.println("enter try");
//			int c=10/0;
//			System.out.println("from try after exception");
//		}
//
////args known as command line arguments
//		
//		catch(Exception e) {//exception is an object
//			//System.out.println("from catch");`
//			e.printStackTrace();
//		}
//			catch(ArithmeticException e)
//			{
//				e.printStackTrace();//
//			}
//		//
//		finally {
//			System.out.println("from finally");
//		}
//		System.out.println("program task completed");
//	}
//
//}
